# Generated by Django 4.1 on 2023-05-16 01:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Citizen",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("citizen_id", models.AutoField(primary_key=True, serialize=False)),
                ("citizen_aadhaar", models.CharField(max_length=12, unique=True)),
                ("citizen_fname", models.CharField(max_length=100)),
                ("citizen_email", models.EmailField(max_length=100, unique=True)),
                ("citizen_phno", models.CharField(max_length=10, unique=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("last_login", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
