# Generated by Django 4.1 on 2023-05-15 11:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Police",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("police_id", models.AutoField(primary_key=True, serialize=False)),
                ("police_name", models.CharField(max_length=100)),
                ("police_email", models.EmailField(max_length=100, unique=True)),
                ("police_phno", models.CharField(max_length=10, unique=True)),
                ("police_city", models.CharField(max_length=100)),
                ("police_locality", models.CharField(max_length=100)),
                ("police_post", models.CharField(max_length=100)),
                ("is_staff", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("last_login", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
