# Generated by Django 4.1 on 2023-05-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PolicePortal", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="police",
            name="police_id",
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
